### ISSUE TITLE
About training instructions

### ISSUE THREAD

**Issue by PilgrimMay** [CityU-AIM-Group/NLTE#2] opened 2022-05-23 08:57 UTC
sorry to bother, I wonder if you could give some specific examples of training instructions about city->foggy and voc->water?

**Comment by xinyuliu-jeffrey** [comment] 2022-05-23 09:10
Hi, you may just follow the README to train models. After you changed the path of dataset in path_catalog.py, you can train them.
For City->Foggy, step 4 is not necessary, just run
python -m torch.distributed.launch --nproc_per_node=$NGPUS ./tools/train_net.py --config-file .configs/da_faster_rcnn/e2e_da_c2f.yaml OUTPUT_DIR city_to_foggy.
For voc->water, run step4 to generate noise and change --config-file .

**Comment by PilgrimMay** [comment] 2022-05-23 09:51
Should I change the value of _C.DATASETS.ANNOTATIONS in defaults.py and ANNOTATIONS in e2e_da_c2f.yaml? Their initial values are None and there is a following error: AssertionError: Invalid type <class 'NoneType'> for key ANNOTATIONS; valid types = {<class 'float'>, <class 'int'>, <class 'tuple'>, <class 'bool'>, <class 'str'>, <class 'list'>}.
 
And another question. In the README, training instructions refer to DATASETS.ANNOTATIONS Noisy_Annotations_per_$NOISYRATE, how should I set this part?

**Comment by xinyuliu-jeffrey** [comment] 2022-05-23 11:50
@PilgrimMay For city->foggy, you don't need to generate noise on labels. So the command to train it is :

python tools/train_net.py --config-file ./configs/da_faster_rcnn/e2e_da_c2f.yaml OUTPUT_DIR city_to_foggy

I think you don't really need to modify the DATASETS.ANNOTATIONS, and leave them as None shall not raise error if you set up the environment properly.

For voc-> water, you may generate noise with the code in VOCdevkit dir first, then change the Noisy_Annotations_per_$NOISYRATE to certain degree noise. E.g. Noisy_Annotations_per_0.200000.

**Comment by PilgrimMay** [comment] 2022-05-23 15:23
sorry to bother so late, when I train city->foggy, there is such a error: RuntimeError: Given input size: (2048x4x4). Calculated output size: (2048x0x0). Output size is too small. Whether should I change some options?

**Comment by xinyuliu-jeffrey** [comment] 2022-05-24 02:12
@PilgrimMay Could you please provide a screenshot of the error for me to locate the error?

**Comment by PilgrimMay** [comment] 2022-05-24 02:17
![image](https://user-images.githubusercontent.com/43989001/169935087-e7613889-a82f-4666-9b93-cd750da232e2.png)

**Comment by xinyuliu-jeffrey** [comment] 2022-05-24 02:20
@PilgrimMay It may due to your RoI size is small. Have you modified ROI_BOX_HEAD.POOLER_RESOLUTION or INPUT.MIN_SIZE_TRAIN?

**Comment by PilgrimMay** [comment] 2022-05-24 02:25
I use the default potions. 
_C.MODEL.ROI_BOX_HEAD.POOLER_RESOLUTION = 14
_C.INPUT.MIN_SIZE_TRAIN = (800,)

**Comment by xinyuliu-jeffrey** [comment] 2022-05-24 02:29
@PilgrimMay That's strange. Have you set your dataset properly? Unfortunately I could not reproduce your issue.

**Comment by xinyuliu-jeffrey** [comment] 2022-05-24 02:30
@PilgrimMay You may not refer to default.py. The configs will be replaced by the configs in configs/da_faster_rcnn/e2e_da_c2f.yaml. You may check the settings in the yaml file.

**Comment by PilgrimMay** [comment] 2022-05-24 02:36
Yeah! In the yaml file, _C.MODEL.ROI_BOX_HEAD.POOLER_RESOLUTION is 7. I change it to 14 and everything is OK. Thank you very much!

**Comment by xinyuliu-jeffrey** [comment] 2022-05-24 02:40
@PilgrimMay Glad to hear that. However, I think the code is executable when setting MODEL.ROI_BOX_HEAD.POOLER_RESOLUTION to 7. If you have not modified the code, you may email me the log for me to identify the problem.

**Comment by PilgrimMay** [comment] 2022-05-24 02:52
I'm using pytorch 1.3.1 instead of 1.0 version, maybe that's the problem. I would reconfigure the environment to try again.

**Comment by xinyuliu-jeffrey** [comment] 2022-05-24 02:57
@PilgrimMay OK. I will close the issue now, feel free to open it if there are any other problems.

**Closed as completed by xinyuliu-jeffrey** 2022-05-24 02:57 UTC

**Comment by PilgrimMay** [comment] 2022-07-18 07:00
Sorry to bother again, could you tell me which part of the code implements the feature aggregation module?

**Comment by xinyuliu-jeffrey** [comment] 2022-07-18 07:25
@PilgrimMay Please refer to https://github.com/CityU-AIM-Group/NLTE/blob/a111390bcc38bd0c759a3a9d971a7d9defce88fb/maskrcnn_benchmark/modeling/roi_heads/box_head/roi_box_predictors.py#L50-L70

**Comment by PilgrimMay** [comment] 2022-07-18 07:26
Thank you!
